### ISSUE TITLE
boost linking problem for test modules with clang

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclus#601]
Introduced with efa6fc88823, test modules now fail to link to boost correctly when using clang. To reproduce this, you will have to include #600 first.

Linking CXX shared library ../../../../lib/Models/Facility/TestFacility/libTestFacility.dylib
Undefined symbols for architecture x86_64:
  "boost::system::system_category()", referenced from:
      ___cxx_global_var_init3 in test_facility.cc.o
  "boost::system::generic_category()", referenced from:
      ___cxx_global_var_init1 in test_facility.cc.o
      ___cxx_global_var_init2 in test_facility.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [lib/Models/Facility/TestFacility/libTestFacility.dylib] Error 1
make[1]: **\* [tests/Models/Facility/TestFacility/CMakeFiles/TestFacility.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....

I would suggest that we have a policy henceforth to require pull requests that deal with changing the build system be run through our Insam machine first. Does that seem reasonable, @scopatz?
