### ISSUE TITLE
Can't import typesystem using python

### ISSUE THREAD

**Issue by nuclearkatie** [cyclus/cyclus#1810]
Had this issue on a docker container I use for development and replicated on a fresh docker image with current latest cyclus, cycamore, and cymetric.

While trying to import cymetric, the cyclus typesystem is [imported](https://github.com/cyclus/cymetric/blob/2645e8f6c0453db21308aa91cb5406b8265aa01e/cymetric/__init__.py#L4). Or by calling the cyclus typesytem import directly, the following error is obtained:

```
Cell In[2], line 1
----> 1 from cyclus.typesystem import *

File typesystem.pyx:1, in init cyclus.typesystem()

File lib.pyx:42, in init cyclus.lib()

ImportError: cannot import name typesystem
```

This error completely prevents cymetric from being used

**Comment by gonuke** [comment]
@bennibbelink - any chance this is related to recent cython changes?  If so, maybe we aren't testing for it

**Comment by nuclearkatie** [comment]
I think, from git bisecting, that this is the commit [remove hacky imports in __init__.py](https://github.com/cyclus/cyclus/commit/4a2663bd2f7e861d64de56f7797fd50205a3cc8c) which was part of #1809

**Comment by bennibbelink** [comment]
@nuclearkatie do you use an image with dependencies installed via conda or apt?

**Comment by nuclearkatie** [comment]
I built an image from apt-deps in the cyclus docker file and then manually followed the apt instructions for cyclus, cycamore, and cymetric

**Comment by bennibbelink** [comment]
I just tried this, all tests pass and I can import `cymetric` (and `cyclus.typesystem`)  in a python shell
```bash
# in host shell
docker build -f docker/Dockerfile --target apt-deps -t apt-deps .
docker run -it -v <your host cyclus dir>:/cyclus -v <your host cycamore dir>:/cycamore -v <your host cymetric dir>:/cymetric apt-deps
# in container shell
cd /cyclus && python3 install.py -j 4 --allow-milps
cd /cycamore && python3 install.py -j 4 --allow-milps
cd /cymetric && python3 -m pip install --target $(python3 -m site --user-site) .
export PATH=~/.local/bin:$PATH
# ... run tests
```

**Comment by bennibbelink** [comment]
@nuclearkatie is this still blocking you?

**Comment by nuclearkatie** [comment]
I haven't gotten to the bottom of it, but I'm also able to get around it by skipping that particular import. The problem may be on my end because it doesn't seem reproducible... I'll close this unless it comes up again and is clearly reproducible
